### ISSUE TITLE
RP not showing up on discord 

### ISSUE THREAD

**Issue by owobon** [demaisj/soundcloud-rp#12]
i did the debug command and npm start and heres all my console says

![image](https://user-images.githubusercontent.com/34631499/45788162-e32e6000-bc46-11e8-9c39-057d05ff1b63.png)

**Comment by demaisj** [comment]
Something seems wrong with the rpc connection. Can you give me debug logs when *starting* the server ..? This excerpt is not really helpful.

**Comment by owobon** [comment]
![image](https://user-images.githubusercontent.com/34631499/45934836-e3459d00-bf71-11e8-9f74-e3d2d49abbc9.png)

**Comment by demaisj** [comment]
I think there is a problem with the soundcloud ClientID you are using, the server seems to fail to communicate with soundcloud. Please double check it.

**Comment by owobon** [comment]
alright i managed to fix it thank you very much!
