### ISSUE TITLE
Failed to connect to discord on Raspbian 9

### ISSUE THREAD

**Issue by TotomInc** [demaisj/soundcloud-rp#14]
I'm trying to setup soundcloud-rp on my Raspberry PI running on Raspbian 9.

Running `DEBUG=soundcloud-rp:* npm run start` gives me:

```bash
  soundcloud-rp:trace rpc.constructor +0ms
  soundcloud-rp:trace rpc.init +7ms
  soundcloud-rp:trace rpc.connect +2ms
  soundcloud-rp:rpc Connecting to discord... +0ms
  soundcloud-rp:server Listening on port 7769 +768ms
  soundcloud-rp:trace rpc.connect.fail +11ms
  soundcloud-rp:rpc Failed to connect to discord Error: Could not connect
    at Socket.onerror (/home/pi/soundcloud-rp/node_modules/discord-rpc/src/transports/IPC.js:32:16)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9) +1ms
  soundcloud-rp:rpc Trying again in 10 seconds... +5ms
```

- Node: v8.11.4 (latest LTS)
- NPM: v5.6.0

EDIT: switched to latest Node (10.11.0) and it still gives the same error.

**Comment by TotomInc** [comment]
My idea was to run the server on my Raspberry PI then the userscript which is executed on another computer (in the same network) will connect to the Raspberry PI using the local IP address instead of the localhost.

Did discord-rpc requires the Discord app to be launched and in background to login?

**Comment by demaisj** [comment]
Hi,
You need to run the discord client alongside the server for Rich Presence to work. This is a limitation from the Rich Presence protocol itself. This kind of setup will not work.

**Comment by TotomInc** [comment]
Thanks for the answer, I thought it worked while I was logged on another computer. I'll see if I can run Discord in the background as a service.
