### ISSUE TITLE
Can't firgure out how to add artwork

### ISSUE THREAD

**Issue by TheDJKitty** [demaisj/soundcloud-rp#16]
Ive tried following the instructions, but i dont understand where to paste the clientID at or API key at

**Comment by demaisj** [comment]
Hi,
You should paste those values in the `config/default.json` file. 
Using a editor, your file should finally look like this (obviously after pasting the keys):
![image](https://user-images.githubusercontent.com/2797696/47244250-0e969d00-d3f5-11e8-8c0b-0872946b7bab.png)
don't forget to set uploadArtwork to true.

**Comment by TheDJKitty** [comment]
Thank you sooo much i got it to work!
