### ISSUE TITLE
Can't retrieve my ClientID

### ISSUE THREAD

**Issue by Ephemeralic** [demaisj/soundcloud-rp#2]
Pasting the command in the console on SoundCloud just throws an error. 

http://prntscr.com/k87miq

**Comment by demaisj** [comment]
Hi,

The command is outdated, and I haven't updated the README.
I have a workaround for you, but it is quite complicated:
1. Hit F12 to open the devtools
2. Go to **Network** tab
3. Filter `api-v2.soundcloud.com`
4. Click on the first result
    If there is no results, try changing page on Soundcloud to trigger some requests
5. Scroll down to the **Query String Parameters** section
6. Look for **client_id** and copy the value

Hope this helps

**Comment by Ephemeralic** [comment]
Thank you!
