### ISSUE TITLE
Weird error

### ISSUE THREAD

**Issue by Dipsh1t** [demaisj/soundcloud-rp#26]
I'm getting this strange error when trying to start the server
![nodejs error](https://user-images.githubusercontent.com/44480344/79326917-4c0db500-7f1c-11ea-856b-fd7294768545.PNG)

**Comment by demaisj** [comment]
You didn't install the dependencies by running the "npm install" command

--
Jordan DEMAISON
jordan.demaison@gmail.com
+33 (0)6 95 70 83 62
https://demaisj.me
