### ISSUE TITLE
Windows Script Host error

### ISSUE THREAD

**Issue by adampai** [demaisj/soundcloud-rp#27]
So, I did everything as it was written in the instructions, however during the last stop I encounter a major problem. I can't install the .js file. This screen pops up. https://imgur.com/7sEptLo
I've tried restarting my PC, as well as searching for a solution on the Internet. Nothing seems to work, it also says that there's an incorrect line in the code in line 13, but as far as I know, there's none.

**Comment by demaisj** [comment]
you need to run the server using the "npm run start' command as described in the installation instructions

**Comment by adampai** [comment]
It somehow works now, thank you, altough I have another problem, artwork upload doesn't seem to work for me. Can you help me with that too?

**Comment by adampai** [comment]
https://imgur.com/iXcVohn
This is the final default.json file.

**Comment by adampai** [comment]
Resolved.
