### ISSUE TITLE
Songs not showing up

### ISSUE THREAD

**Issue by xuuuy** [demaisj/soundcloud-rp#4]
Hello I think I got all of it working 
https://i.imgur.com/r81pWnd.png its telling me this 
I also downloaded tampermonkey and everything else.
but it's still not showing the music i'm playing.

**Comment by demaisj** [comment]
Hello,
Could you provide me more details about your issue ?
In order to troubleshoot the server, run it with the `DEBUG=soundcloud-rp:* & npm run start` in a cmd, then reload SoundCloud and play some tracks. The server will print debug messages and errors.

**Comment by xuuuy** [comment]
I got it working now I don't know what I did to get it working but thanks for the help!
