### ISSUE TITLE
It is normal?

### ISSUE THREAD

**Issue by Hiteke** [demaisj/soundcloud-rp#5]
npm WARN soundcloud-rp@2.0.2 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fse
vents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"}

**Comment by demaisj** [comment]
Hello,
Those warnings from npm are normal, nothing to worry about.
