### ISSUE TITLE
RP discord doesn't work

### ISSUE THREAD

**Issue by Hiteke** [demaisj/soundcloud-rp#6]
What do? If RP discord doesn't work

**Comment by Hiteke** [comment]
Can you help me in discord or make a video guide?

**Comment by Hiteke** [comment]
The server is working, soundcloud is working, but discord does not show that I'm listening

**Comment by demaisj** [comment]
Could you provide me more details about your issue ?
In order to troubleshoot the server, run it with the `DEBUG=soundcloud-rp:* & npm run start` in a cmd, then reload SoundCloud and play some tracks. The server will print debug messages and errors.

**Comment by Hiteke** [comment]
Ok

**Comment by Hiteke** [comment]
I have windows 7
DEBUG=soundcloud-rp what?

**Comment by demaisj** [comment]
sorry i misspelled the command to run, it is `set DEBUG=soundcloud-rp:* & npm run start`

**Comment by Hiteke** [comment]
set DEBUG=soundcloud-rp

**Comment by Hiteke** [comment]
soundcloud-rp:trace rpc.constructor +0ms
  soundcloud-rp:trace rpc.init +3ms
  soundcloud-rp:trace rpc.connect +1ms
  soundcloud-rp:rpc Connecting to discord... +0ms
  soundcloud-rp:server Listening on port 7769 +348ms
  soundcloud-rp:trace rpc.event.ready +622ms
  soundcloud-rp:trace rpc.connect.success +1ms
  soundcloud-rp:rpc Connected to discord! +0ms
  soundcloud-rp:trace client.connection w9FipoPkHYTWr5g1AAAA +1s
  soundcloud-rp:trace client.event w9FipoPkHYTWr5g1AAAA activity { url: 'https:/
/soundcloud.com/exile_music/pompeii', pos: 117 } +21ms
  soundcloud-rp:trace activity { url: 'https://soundcloud.com/exile_music/pompei
i', pos: 117 } +6ms
  soundcloud-rp:trace rpc.getActivity +1ms
  soundcloud-rp:activity getting track info... +1ms
  soundcloud-rp:trace soundcloud.getTrackData https://soundcloud.com/exile_music
/pompeii +1ms
  soundcloud-rp:trace client.event w9FipoPkHYTWr5g1AAAA activity { url:
   'https://soundcloud.com/marshmellomusic/stars-original-mix?in=marshmellomusic
/sets/joytime-ii',
  pos: 4 } +31ms
  soundcloud-rp:trace activity { url:
   'https://soundcloud.com/marshmellomusic/stars-original-mix?in=marshmellomusic
/sets/joytime-ii',
  pos: 4 } +2ms
  soundcloud-rp:activity LOCKED state, we are already updating activity +1ms
  soundcloud-rp:trace client.event w9FipoPkHYTWr5g1AAAA activity { url:
   'https://soundcloud.com/marshmellomusic/stars-original-mix?in=marshmellomusic
/sets/joytime-ii',
  pos: 14 } +2ms
  soundcloud-rp:trace activity { url:
   'https://soundcloud.com/marshmellomusic/stars-original-mix?in=marshmellomusic
/sets/joytime-ii',
  pos: 14 } +1ms
  soundcloud-rp:activity LOCKED state, we are already updating activity +0ms
  soundcloud-rp:trace client.event w9FipoPkHYTWr5g1AAAA activity { url:
   'https://soundcloud.com/marshmellomusic/stars-original-mix?in=marshmellomusic
/sets/joytime-ii',
  pos: 24 } +1ms
  soundcloud-rp:trace activity { url:
   'https://soundcloud.com/marshmellomusic/stars-original-mix?in=marshmellomusic
/sets/joytime-ii',
  pos: 24 } +1ms
  soundcloud-rp:activity LOCKED state, we are already updating activity +1ms
  soundcloud-rp:trace client.event w9FipoPkHYTWr5g1AAAA activity { url:
   'https://soundcloud.com/marshmellomusic/stars-original-mix?in=marshmellomusic
/sets/joytime-ii',
  pos: 34 } +8s
  soundcloud-rp:trace activity { url:
   'https://soundcloud.com/marshmellomusic/stars-original-mix?in=marshmellomusic
/sets/joytime-ii',
  pos: 34 } +2ms
  soundcloud-rp:trace rpc.getActivity +1ms
  soundcloud-rp:activity getting track info... +1ms
  soundcloud-rp:trace soundcloud.getTrackData https://soundcloud.com/marshmellom
usic/stars-original-mix?in=marshmellomusic/sets/joytime-ii +0ms
  soundcloud-rp:trace client.event w9FipoPkHYTWr5g1AAAA activity { url:
   'https://soundcloud.com/marshmellomusic/stars-original-mix?in=marshmellomusic
/sets/joytime-ii',
  pos: 44 } +10s
  soundcloud-rp:trace activity { url:
   'https://soundcloud.com/marshmellomusic/stars-original-mix?in=marshmellomusic
/sets/joytime-ii',
  pos: 44 } +0ms
  soundcloud-rp:trace rpc.getActivity +1ms
  soundcloud-rp:activity getting track info... +0ms
  soundcloud-rp:trace soundcloud.getTrackData https://soundcloud.com/marshmellom
usic/stars-original-mix?in=marshmellomusic/sets/joytime-ii +1ms``

**Comment by Hiteke** [comment]
soundcloud-rp:trace rpc.constructor +0ms
  soundcloud-rp:trace rpc.init +3ms
  soundcloud-rp:trace rpc.connect +1ms
  soundcloud-rp:rpc Connecting to discord... +0ms
  soundcloud-rp:server Listening on port 7769 +348ms
  soundcloud-rp:trace rpc.event.ready +622ms
  soundcloud-rp:trace rpc.connect.success +1ms
  soundcloud-rp:rpc Connected to discord! +0ms
  soundcloud-rp:trace client.connection w9FipoPkHYTWr5g1AAAA +1s
  soundcloud-rp:trace client.event w9FipoPkHYTWr5g1AAAA activity { url: 'https:/
/soundcloud.com/exile_music/pompeii', pos: 117 } +21ms
  soundcloud-rp:trace activity { url: 'https://soundcloud.com/exile_music/pompei
i', pos: 117 } +6ms
  soundcloud-rp:trace rpc.getActivity +1ms
  soundcloud-rp:activity getting track info... +1ms
  soundcloud-rp:trace soundcloud.getTrackData https://soundcloud.com/exile_music
/pompeii +1ms
  soundcloud-rp:trace client.event w9FipoPkHYTWr5g1AAAA activity { url:
   'https://soundcloud.com/marshmellomusic/stars-original-mix?in=marshmellomusic
/sets/joytime-ii',
  pos: 4 } +31ms
  soundcloud-rp:trace activity { url:
   'https://soundcloud.com/marshmellomusic/stars-original-mix?in=marshmellomusic
/sets/joytime-ii',
  pos: 4 } +2ms
  soundcloud-rp:activity LOCKED state, we are already updating activity +1ms
  soundcloud-rp:trace client.event w9FipoPkHYTWr5g1AAAA activity { url:
   'https://soundcloud.com/marshmellomusic/stars-original-mix?in=marshmellomusic
/sets/joytime-ii',
  pos: 14 } +2ms
  soundcloud-rp:trace activity { url:
   'https://soundcloud.com/marshmellomusic/stars-original-mix?in=marshmellomusic
/sets/joytime-ii',
  pos: 14 } +1ms
  soundcloud-rp:activity LOCKED state, we are already updating activity +0ms
  soundcloud-rp:trace client.event w9FipoPkHYTWr5g1AAAA activity { url:
   'https://soundcloud.com/marshmellomusic/stars-original-mix?in=marshmellomusic
/sets/joytime-ii',
  pos: 24 } +1ms
  soundcloud-rp:trace activity { url:
   'https://soundcloud.com/marshmellomusic/stars-original-mix?in=marshmellomusic
/sets/joytime-ii',
  pos: 24 } +1ms
  soundcloud-rp:activity LOCKED state, we are already updating activity +1ms
  soundcloud-rp:trace client.event w9FipoPkHYTWr5g1AAAA activity { url:
   'https://soundcloud.com/marshmellomusic/stars-original-mix?in=marshmellomusic
/sets/joytime-ii',
  pos: 34 } +8s
  soundcloud-rp:trace activity { url:
   'https://soundcloud.com/marshmellomusic/stars-original-mix?in=marshmellomusic
/sets/joytime-ii',
  pos: 34 } +2ms
  soundcloud-rp:trace rpc.getActivity +1ms
  soundcloud-rp:activity getting track info... +1ms
  soundcloud-rp:trace soundcloud.getTrackData https://soundcloud.com/marshmellom
usic/stars-original-mix?in=marshmellomusic/sets/joytime-ii +0ms
  soundcloud-rp:trace client.event w9FipoPkHYTWr5g1AAAA activity { url:
   'https://soundcloud.com/marshmellomusic/stars-original-mix?in=marshmellomusic
/sets/joytime-ii',
  pos: 44 } +10s
  soundcloud-rp:trace activity { url:
   'https://soundcloud.com/marshmellomusic/stars-original-mix?in=marshmellomusic
/sets/joytime-ii',
  pos: 44 } +0ms
  soundcloud-rp:trace rpc.getActivity +1ms
  soundcloud-rp:activity getting track info... +0ms
  soundcloud-rp:trace soundcloud.getTrackData https://soundcloud.com/marshmellom
usic/stars-original-mix?in=marshmellomusic/sets/joytime-ii +1ms

**Comment by Hiteke** [comment]
Problem with discord?

**Comment by demaisj** [comment]
I think there is a problem with the Soundcloud ClientID you provided. It could be invalid.

**Comment by Hiteke** [comment]
Recopied clientid

**Comment by Hiteke** [comment]
Everything works for me now.
