### ISSUE TITLE
error on "npm run start"

### ISSUE THREAD

**Issue by frozaum** [demaisj/soundcloud-rp#7]
![image](https://user-images.githubusercontent.com/34042085/43734882-7f2041e8-998f-11e8-9754-6116e759003c.png)

**Comment by demaisj** [comment]
Hello,
Did you run the `npm install` command before running `npm run start`?
Are you running the commands in the  right folder?

**Comment by frozaum** [comment]
i forget to see the part to npm install lol
but yeah, now is working.
