### ISSUE TITLE
I can't figure out what the problem is here....

### ISSUE THREAD

**Issue by ryanturner328** [demaisj/soundcloud-rp#8]
I did `npm install`, and it installed. I did `npm run start` and it came back with errors. 
![soundcloud-discord-rpc-error](https://user-images.githubusercontent.com/30201188/43737968-afb1e002-9988-11e8-91cc-e4b3623dc3a5.PNG)

**Comment by demaisj** [comment]
Hello,
Are you sure you are in the right folder and the file `package.json` (still?) exists? This shouldn't be happening, this is a problem on your side. If you lost the file you can try re-downloading this program.

**Comment by Hiteke** [comment]
@demaisj  Im help you my discord is Hiteke#2455

**Comment by Hiteke** [comment]
@ryanturner328  Im help you my discord Hiteke#2455

**Comment by ryanturner328** [comment]
@demaisj I think I was in the wrong folder, But I think I got it now.

@Hiteke I sent you a friend request for your support, but I don't need it anymore.

**Comment by demaisj** [comment]
Ok, I'm closing this issue then.
